### PR TITLE
Added constants

### PR DESCRIPTION
**Pull request by jfren484**
Issue https://github.com/Garethp/ScreepsAutocomplete/issues/60 requested new constants. I've added them.

Ignore my first 2 commits (the 2nd just undoes the 1st one, so no net change). I thought I needed to add definitions for modules and require(), but I really just needed to add node as a library in WebStorm.

### CODE REVIEW

**Comment by Garethp** [comment]
Sorry about that, I've been a bit swamped lately, and haven't played this in a long time, so it's slipped my notice

**Comment by jfren484** [comment]
No problem. Happy to help!

**Comment by jfren484** [comment]
Hey Gareth, it looks like there are quite a few changes to Screeps that aren't in this repository yet (e.g. Market, Map, many properties and functions on existing objects). I don't mind adding those if you're busy, but if it's something you're planning to do, I don't want to duplicate effort.

**Comment by Garethp** [comment]
I'm planning to set aside a couple of hours at some point to redo the library from scratch, I'm just not sure when I'll get around to it

**Pull request merged**
